### PR TITLE
updated the gitignore (little more inlusive)

### PR DESCRIPTION
**Pull request by djreisch**
Adds basic gitignore statements which come in handy when compiling in VS

### CODE REVIEW

**Comment by akorb** [comment]
Thanks for this pull request.
The `/packages` folder should be excluded too.

**Comment by djreisch** [comment]
shouldn't it be `packages/`? I added `/packages` back in so PR ready

EDIT: Added the backend forward slash so it looks nicer. Double checked it works and it does

**Comment by akorb** [comment]
There is a difference.

A trailing `/` (`packages/`) says "ignore directories named `packages` anywhere"
A leading `/` (`/packages`) says "ignore files/directories named `packages` in the same folder as the .gitignore"

Both (`/packages/`) says: Ignore the directory named `packages` in the same folder as the .gitignore

I think we need the last one.

**Comment by djreisch** [comment]
I pushed the change to the branch. I had assumed you would want package folders omitted in sub-directories as well. But you're good to go, it's `/packages/` which will only omit the packages _folder_ in the root directory

**Comment by akorb** [comment]
I don't see a push

**Comment by djreisch** [comment]
Sorry about that, I pushed to master not the branch to merge. Updated now

**Pull request merged**
