### PR TITLE
Issue #33 : Fix library path(s) readout.

### PR DESCRIPTION
**Pull request by Neuroquila-n8fall**
**Targets: #33 #34 and related.**
While diagnosing the bug i found that the .vdf file has changed apparently. Since the tool is only interested in working paths of library folders, we can safely assume that any "path" occurrence inside the library VDF file is considered a path that should be checked for downloads.
This approach is to be considered first and foremost a quick fix and secondly as a brute force method as it's now cycling through each line of the file, checking for the "path" keyword and extracting the path portion of it. Then the path is being verified. Since this VDF file shouldn't have too many entries this approach shouldn't impact startup performance. **I strongly recommend checking this against other installations before releasing it into the wild. I have the feeling that this library file can vary heavily between systems.**

### CODE REVIEW

**Comment by akorb** [comment]
Thank you very much for your Pull Request, I appreciate your work in this!

While checking and verifying your code, I found an simpler fix. They simply changed the format of the `libraryfolders.vdf` file.

Old format:

```
"libraryfolders"
{
	"contentstatsid"		"3187975095530642742"
	"1"         "E:\\SteamLibrary"
	"2"         "F:\\SteamLibrary"
}
```

New format:

```
"libraryfolders"
{
	"contentstatsid"		"3187975095530642742"
	"1"
	{
		"path"		"E:\\SteamLibrary"
		"label"		""
		"mounted"		"1"
		"contentid"		"7743665490897330647"
	}
	"2"
	{
		"path"		"F:\\SteamLibrary"
		"label"		"NO_LABEL"
		"mounted"		"1"
		"contentid"		"3667450138305782071"
	}
}
```

I hope that I could fix this problem with this commit: https://github.com/akorb/SteamShutdown/commit/f1988dc42b88b2c385ebae492538a29d1ea30516

I also consider the `mounted` flag in the new format: https://github.com/akorb/SteamShutdown/commit/622dac1d632c54135fbfd0c72a40381e7b00639e

**Comment by akorb** [comment]
Ah, btw, how do you know it's related to #33 ?

**Comment by akorb** [comment]
Already some people reported that my fix seems to work. That's why I just uploaded a new release. Still, thanks for your effort! :)

**Comment by Neuroquila-n8fall** [comment]
> Ah, btw, how do you know it's related to #33 ?

Just telling from the exception :)



> Already some people reported that my fix seems to work. That's why I just uploaded a new release. Still, thanks for your effort! :)

You're welcome! Glad it worked without pulling this "hack" :)

**Pull request closed without merging**
